
name: Shell script

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
     shell_job:
         runs-on: ubuntu-latest
         steps:
         - name: Checkout repo
           uses: actions/checkout@v5
           
         - name: welcome message 
           run: |
             echo "welcome"
             ls
             cat README.md

         - name: Install cowsay
           run: ./shell.sh